### ISSUE TITLE
Inconsistent menus

### ISSUE THREAD

**Issue by filiptronicek** [aperta-principium/Interclip#127]
Inconsistent menus can be found on these pages:
- The receive page
- The file upload page
- The about page

Normal menu:
![image](https://user-images.githubusercontent.com/29888641/120892061-98c6ba80-c60c-11eb-8182-ea8f07c362fd.png)
The weird design found on the aforementioned pages:
![image](https://user-images.githubusercontent.com/29888641/120892072-ae3be480-c60c-11eb-963d-981555ba2a3e.png)

**_This also happens on mobile_**

**Comment by filiptronicek** [comment]
It's probably one of the styles, as @bigInt found out, but I am struggling in finding the exact style. This style is probably located in https://github.com/aperta-principium/Interclip/blob/main/css/index.css

**Comment by bigint** [comment]
Good job 👏🏻
