### ISSUE TITLE
[mobile] Overflowing text on receive button

### ISSUE THREAD

**Issue by filiptronicek** [aperta-principium/Interclip#91]
Tested on an iPhone 12 Pro Max and iPhone 12 both running iOS 14:

<table>
<tr>
	<td> iPhone 12 Pro Max </td>
	<td> iPhone 12 </td>
</tr>
<tr>
	<td> <img src="https://user-images.githubusercontent.com/29888641/113281772-4c968b80-92e6-11eb-9023-9581db49f477.png"> </td>
	<td> <img src="https://user-images.githubusercontent.com/29888641/113281847-659f3c80-92e6-11eb-949f-3b5c416d5f55.png"> </td>
</tr>
</table>

**Comment by miralsuthar** [comment]
I would like to contribute to this issue.

**Comment by filiptronicek** [comment]
@miralsuthar awesome! Please refer to https://github.com/aperta-principium/Interclip/blob/main/CONTRIBUTING.md on how to setup the project. I will assign the issue to you now.
