### ISSUE TITLE
Change the loading animation

### ISSUE THREAD

**Issue by filiptronicek** [aperta-principium/Interclip#93]
This... sucks

![loading animation (current)](https://interclip.app/css/loading-spin.svg)

It was made almost 2 years ago on a site called [loading.io](https://loading.io/), which, well, it's... not the best... quality.
As noted by @svobodavl in a Discord message today, **the dot above the i doesn't even flippin' spin!**

**Comment by svobodavl** [comment]
The dot actually spins. It's just that it doesn't spin with the I, which makes me incredibly sad
